from pynput.keyboard import Controller
controlador = Controller()
controlador.press("G")
controlador.release("G")
controlador.press("A")
controlador.release("A")
controlador.press("R")
controlador.release("R")
controlador.press("U")
controlador.release("U")
controlador.press("C")
controlador.release("C")
controlador.press("O")
controlador.release("O")

